src/TypeShape.Examples/CborSerializer/Converters/PrimitiveConverters.cs, src/TypeShape.Examples/XmlSerializer/Converters/PrimitiveConverters.cs
A couple of converters were delegating `DateTime` serialization to `DateTimeOffset`, which was causing a number of tests to fail in machines with western hemisphere timezones.
Fix https://github.com/eiriktsarpalis/typeshape-csharp/issues/16
cc @AArnott
=> Fix handling of boundary DateTime values in other timezones.

src/TypeShape.Roslyn/Helpers/RoslynHelpers.cs, src/TypeShape.Roslyn/Model/PropertyDataModel.cs, src/TypeShape.Roslyn/TypeShape.Roslyn.csproj, src/TypeShape.SourceGenerator/TypeShape.SourceGenerator.csproj
Following up on #20 this lowers the TypeShape.Roslyn dependency to 3.11. It turns out that the only missing APIs required by this layer is required properties which can be looked up using reflection.
Contributes to https://github.com/eiriktsarpalis/typeshape-csharp/issues/18
cc @AArnott
=> Lower TypeShape.Roslyn Roslyn dependency to 3.11

tests/TypeShape.Tests/TypeShape.Tests.csproj
On the second computer I've cloned this repo down to, the build fails because one of the files the compiler tries to write has a file length that's too long:
'D:\source\typeshape-csharp\tests\TypeShape.Tests\obj\Debug\net8.0\generated\TypeShape.SourceGenerator\TypeShape.SourceGenerator.TypeShapeIncrementalGenerator\TypeShape.Tests.SourceGenProvider.ValueTuple_Int32_Int32_Int32_Int32_Int32_Int32_Int32_Int32_Int32.g.cs' is 261 characters long
It's odd that this path is shorter than my first computer, which has no problem with builds (although many tools and features of Windows are still unable to process this file or even delete it).
I suggest in the interest in making this repo more consumable by more people and machines, that we turn off generated file emission on disk. Folks can always …
=> Stop writing emitted files to disk

PolyType.sln, nuget.config
On clone+build, I get [NU1507](https://learn.microsoft.com/en-us/nuget/reference/errors-and-warnings/nu1507) because I have multiple package sources defined:
"Warning As Error: There are 3 package sources defined in your configuration. When using central package management, please map your package sources with package source mapping (https://aka.ms/nuget-package-source-mapping) or specify a single package source."
Fix by adding a nuget.config
=> Add nuget.config

src/PolyType.SourceGenerator/Model/TypeDeclarationModel.cs, src/PolyType.SourceGenerator/Parser/Parser.Diagnostics.cs, src/PolyType.SourceGenerator/Parser/Parser.cs, src/PolyType.SourceGenerator/SourceFormatter/SourceFormatter.ITypeShapeProvider.cs, src/PolyType.SourceGenerator/SourceFormatter/SourceFormatter.Type.cs, src/PolyType.SourceGenerator/SourceFormatter/SourceFormatter.cs, src/PolyType/GenerateShapeAttribute.cs, tests/PolyType.SourceGenerator.UnitTests/CompilationTests.cs, tests/PolyType.SourceGenerator.UnitTests/DiagnosticTests.cs, tests/PolyType.Tests/TypeShapeProviderTests.cs
Rework the witness type generation scheme so that the `ITypeShapeProvider` is exposed as a generated `ShapeProvider` static property rather than having the witness type implement the interface itself. This is to make sure that the same singleton provider is always returned to users that might need it, which makes it easier to define caches that are keyed on the particular singleton.
cc @AArnott
=> Rework witness type generation scheme.

src/Directory.Build.props
The nuget.org gallery will show a Release Notes tab for packages that carry this metadata. Rather than be obligated to copy the release notes into the metadata directly, I find it convenient to merely link to the release notes on the GitHub release (which I see you already create).
However one change would be necessary in your workflow: I see that you release 0.x.1 to nuget.org, but your tag and github release name are merely v0.x. For this auto-linking to work, the github release must match the nuget version number (with a 'v' prefix added).
So only merge this if you're willing for your next release and tag name to be `v0.24.1`.
And FWIW, my workflow tends to be to run `nbgv tag` locally and push the tag it creates, thereby ensuring that the tag name and the nuget package version always …
=> Add link to release notes to nuget package metadata

.github/workflows/build.yml, Directory.Packages.props, src/Shared/Helpers/ReflectionHelpers.cs, tests/PolyType.Roslyn.Tests/PolyType.Roslyn.Tests.csproj, tests/PolyType.SourceGenerator.UnitTests/CompilationHelpers.cs, tests/PolyType.SourceGenerator.UnitTests/CompilationTests.cs, tests/PolyType.SourceGenerator.UnitTests/PolyType.SourceGenerator.UnitTests.csproj, tests/PolyType.Tests/CborTests.cs, tests/PolyType.Tests/JsonSchemaTests.cs, tests/PolyType.Tests/JsonTests.cs, tests/PolyType.Tests/PolyType.Tests.csproj, tests/PolyType.Tests/TypeShapeProviderTests.cs, tests/PolyType.Tests/XmlTests.cs
Even though net6.0 is now out of support, it provides a good way to test the `netstandard2.0` build of the library in non-Windows environments.
=> Add net6.0 to the test targets

src/PolyType.Examples/CborSerializer/CborSerializer.Builder.cs, src/PolyType.Examples/Cloner/Cloner.Builder.cs, src/PolyType.Examples/ConfigurationBinder/ConfigurationBinder.Builder.cs, src/PolyType.Examples/Counter/Counter.Builder.cs, src/PolyType.Examples/JsonSchema/JsonSchemaGenerator.cs, src/PolyType.Examples/JsonSerializer/JsonSerializer.Builder.cs, src/PolyType.Examples/ObjectMapper/Mapper.Builder.cs, src/PolyType.Examples/PrettyPrinter/PrettyPrinter.Builder.cs, src/PolyType.Examples/RandomGenerator/RandomGenerator.Builder.cs, src/PolyType.Examples/StructuralEquality/StructuralEqualityComparer.Builder.cs, src/PolyType.Examples/Validation/Validator.Builder.cs, src/PolyType.Examples/XmlSerializer/XmlSerializer.Builder.cs, src/PolyType.SourceGenerator/SourceFormatter/SourceFormatter.Constructors.cs, src/PolyType/Abstractions/ConstructorParameterKind.cs, src/PolyType/Abstractions/IConstructorShape.cs, src/PolyType/Abstractions/IObjectTypeShape.cs, src/PolyType/ReflectionProvider/ReflectionConstructorParameterShape.cs, src/PolyType/ReflectionProvider/ReflectionConstructorShape.cs, src/PolyType/ReflectionProvider/ReflectionObjectTypeShape.cs, src/PolyType/ReflectionProvider/ReflectionPropertyShape.cs, src/PolyType/ReflectionProvider/ReflectionTypeShapeProvider.cs, src/PolyType/ReflectionProvider/ReflectionTypeShapeProviderOptions.cs, src/PolyType/SourceGenModel/SourceGenConstructorShape.cs, src/PolyType/SourceGenModel/SourceGenObjectTypeShape.cs, src/Shared/Helpers/CommonHelpers.cs, tests/PolyType.Tests/JsonSchemaTests.cs, tests/PolyType.Tests/ObjectMapperTests.cs, tests/PolyType.Tests/TypeShapeProviderTests.cs
=> Use IReadOnlyList when modelling properties and constructor params

src/PolyType.SourceGenerator/Parser/Parser.Diagnostics.cs
Experimentation suggests that marshalers do not in fact need to be `public`. Merely `internal` allows the source generator to access the types.
=> Fix error message about private marshalers

src/PolyType.SourceGenerator/SourceFormatter/SourceFormatter.ShapeProvider.cs
I've added them only for the ShapeProvider and Witness files, not the partial types annotated with the GenerateShape Attribute as these are under user-control as far as I understand it.
Do you want tests that the attributes are added?
I could not find any tests actually verifying the generated source code or the generated trees.
fixes #102
=> Add ExcludeFromCodeCoverageAttribute to generated ShapeProvider and Witness files

src/PolyType.Examples/PrettyPrinter/PrettyPrinter.Builder.cs, src/PolyType.Examples/PrettyPrinter/PrettyPrinter.cs
`TextWriter` is a more abstract class, which allows for writing directly to streams or STDOUT, which seems a common scenario for this example, rather than being forced to create one large string.
This doesn't preclude use of `StringBuilder` though, since the `StringWriter : TextWriter` class can create or reuse a `StringBuilder` object while conforming to the `TextWriter` type.
=> Base `PrettyPrinter` on `TextWriter` instead of `StringBuilder`

src/PolyType/GenerateShapeAttribute.cs
It isn't necessary, since it only triggers source generation within the compilation of the code that applies it. It's also problematic because some runtimes (e.g. .NET Framework and unity) do not support generic attributes and reflection APIs throw when they encounter it.
=> Never emit the `GenerateShapeAttribute<T>` into a user's assembly

src/PolyType.Roslyn/Model/DerivedTypeModel.cs, src/PolyType.Roslyn/ModelGenerator/TypeDataModelGenerator.cs, src/PolyType.SourceGenerator/Model/UnionShapeModel.cs, src/PolyType.SourceGenerator/Parser/Parser.ModelMapper.cs, src/PolyType.SourceGenerator/Parser/Parser.cs, src/PolyType.SourceGenerator/SourceFormatter/SourceFormatter.FSharpUnion.cs, src/PolyType.SourceGenerator/SourceFormatter/SourceFormatter.Union.cs, src/PolyType/Abstractions/IUnionCaseShape.cs, src/PolyType/ReflectionProvider/FSharpUnionTypeShape.cs, src/PolyType/ReflectionProvider/ReflectionTypeShapeProvider.cs, src/PolyType/ReflectionProvider/ReflectionUnionCaseShape.cs, src/PolyType/SourceGenModel/SourceGenUnionCaseShape.cs, tests/PolyType.Tests/TypeShapeProviderTests.cs
This allows a serializer to know whether they can consider the Tag property to be a 'stable' input into the serialized schema.
=> Add `IUnionCaseShape.IsTagSpecified` property

src/PolyType.Examples/CborSerializer/CborConverterAttribute.cs, src/PolyType.SourceGenerator/PolyTypeKnownSymbols.cs, src/PolyType/Abstractions/AssociatedTypeAttributeAttribute.cs
The `AssociatedTypeAttribute` is functionality for library implementors only, so it should be best hidden behing the "Abstractions" namespace.
FYI @AArnott
=> Move AssociatedTypeAttribute to Abstractions namespace

.editorconfig, PolyType.sln, exclusion.dic
Prevents false positive spelling errors in the VS editor, avoiding blue squiggles under terms, and blue dots in the scrollbar.
=> Add spelling exclusion dictionary

Directory.Build.props
This improves incremental build compilation within the solution, for `netstandard2.0` projects/configurations in particular. It's enabled by default from `net5.0` onwards, but is worth turning on for earlier targets.
I don't believe it impacts any packaged artifacts. It should only speed up builds within this repo.
=> Produce reference assemblies for all projects

Directory.Packages.props, src/Directory.Build.props
This is no longer required on .NET 8+ SDK, and bringing it in manually means getting an older version than what the SDK supplies.
=> Drop SourceLink package reference

src/PolyType.Roslyn/Model/PropertyDataModel.cs, src/PolyType.Roslyn/ModelGenerator/TypeDataModelGenerator.Object.cs, src/PolyType.SourceGenerator/Model/PropertyShapeModel.cs, src/PolyType.SourceGenerator/Parser/Parser.ModelMapper.cs, src/PolyType.SourceGenerator/Parser/Parser.cs, src/PolyType/Abstractions/IParameterShape.cs, tests/PolyType.SourceGenerator.UnitTests/CompilationTests.cs, tests/PolyType.Tests/IsRequiredTests.cs
This gets non-default source-generation constructor paths to be used in the absence of any `required` or `init` properties, when there _are_ properties annotated with `PropertyShapeAttribute.IsRequired` = `true`.
=> Fix source gen reporting of required-by-attribute properties

tests/PolyType.Tests/CborCustomConverterTests.cs
That class was simply re-running `CborTests` instead of its own one test.
=> Fix CborCustomConverterTests tests

src/PolyType.Roslyn/Helpers/RoslynHelpers.cs, tests/PolyType.SourceGenerator.UnitTests/CompilationTests.cs
Fixes a code gen bug where generic type parameters that are set to `default` are assigned `null` by generated code, even when the generic type argument is a value type.
```
51:                 ArgumentStateConstructorFunc = static () => null!,
70:                 DefaultValue = null!,
```
=> Fix bug in source generation around generic ctor parameter with default value

src/PolyType.Roslyn/ModelGenerator/TypeDataModelGenerator.Enumerable.cs, src/PolyType.SourceGenerator/SourceFormatter/SourceFormatter.Object.cs, src/PolyType.TestCases/TestTypes.cs, src/PolyType/Abstractions/AssociatedTypeAttributeAttribute.cs
Fix a bug in the source generator resulting in the use of `HashSet<T>` as the underlying implementation in the deserialization of `IEnumerable<T>` instances.
=> Fix handling of repeated collection occurrences in the source generator.

src/PolyType.Examples/CborSerializer/CborSerializer.Builder.cs, src/PolyType.Examples/CborSerializer/Converters/CborDictionaryConverter.cs, src/PolyType.Examples/CborSerializer/Converters/CborEnumerableConverter.cs, src/PolyType.Examples/Cloner/Cloner.Builder.cs, src/PolyType.Examples/Counter/Counter.Builder.cs, src/PolyType.Examples/JsonSerializer/Converters/JsonDictionaryConverter.cs, src/PolyType.Examples/JsonSerializer/Converters/JsonEnumerableConverter.cs, src/PolyType.Examples/ObjectMapper/Mapper.Builder.cs, src/PolyType.Examples/PrettyPrinter/PrettyPrinter.Builder.cs, src/PolyType.Examples/RandomGenerator/RandomGenerator.Builder.cs, src/PolyType.Examples/StructuralEquality/StructuralEqualityComparer.Builder.cs, src/PolyType.Examples/Utilities/Helpers.cs, src/PolyType.Examples/Utilities/PooledList.cs, src/PolyType.Examples/Validation/Validator.Builder.cs, src/PolyType.Examples/XmlSerializer/Converters/XmlDictionaryConverter.cs, src/PolyType.Examples/XmlSerializer/Converters/XmlEnumerableConverter.cs, src/PolyType.Examples/XmlSerializer/XmlSerializer.Builder.cs, src/PolyType.Roslyn/KnownSymbols.cs, src/PolyType.Roslyn/Model/EnumerableDataModel.cs, src/PolyType.Roslyn/ModelGenerator/TypeDataModelGenerator.Enumerable.cs, src/PolyType.SourceGenerator/SourceFormatter/SourceFormatter.Enumerable.cs, src/PolyType.TestCases/TestTypes.cs, src/PolyType/Abstractions/IEnumerableTypeShape.cs, src/PolyType/ReflectionProvider/ReflectionEnumerableTypeShape.cs, src/PolyType/ReflectionProvider/ReflectionTypeShapeProvider.cs, src/PolyType/SourceGenModel/SourceGenEnumerableTypeShape.cs, tests/PolyType.Tests/JsonTests.cs, tests/PolyType.Tests/TypeShapeProviderTests.cs
Extends the `IEnumerableTypeShape` type to include support for types implementing `IAsyncEnumerable<T>`. Note that this is a breaking change cc @AArnott
=> Add support for types implementing `IAsyncEnumerable<T>`

src/PolyType.Roslyn/ModelGenerator/TypeDataModelGenerator.Dictionary.cs, src/PolyType/ReflectionProvider/MemberAccessors/IReflectionMemberAccessor.cs, src/PolyType/ReflectionProvider/MemberAccessors/ReflectionEmitMemberAccessor.cs, src/PolyType/ReflectionProvider/MemberAccessors/ReflectionMemberAccessor.cs, src/PolyType/ReflectionProvider/ReflectionDictionaryTypeShape.cs, src/PolyType/ReflectionProvider/ReflectionEnumerableTypeShape.cs, src/PolyType/ReflectionProvider/ReflectionTypeShape.cs, tests/PolyType.Tests/CollectionsWithComparersTests.cs
As part of this, I simplify some code and reuse more delegates to reduce GC pressure. I also noticed through an added test that sourcegen and reflection shape providers produced diverging construction strategies for IDictionary. I unified them (to the mutable strategy rather than span, since that works on non-Emit reflection and is probably faster in most or all cases).
=> Fix NotImplementedException thrown for `IDictionary<K, V>` with a comparer

src/PolyType.Roslyn/ModelGenerator/TypeDataModelGenerator.Object.cs, src/PolyType.Roslyn/ModelGenerator/TypeDataModelGenerator.cs, src/PolyType.SourceGenerator/SourceFormatter/SourceFormatter.Dictionary.cs, src/PolyType.SourceGenerator/SourceFormatter/SourceFormatter.Enumerable.cs, src/PolyType.SourceGenerator/SourceFormatter/SourceFormatter.Object.cs, src/PolyType.SourceGenerator/SourceFormatter/SourceFormatter.cs, src/PolyType/SourceGenModel/SourceGenObjectTypeShape.cs, src/PolyType/SourceGenModel/SourceGenTypeShape.cs, tests/PolyType.Tests/AssociatedTypesTests.cs
This allows associated types to be generated from enumerable and dictionary shapes, which were missing before.
=> Generate associated types from more than just object type shapes

.editorconfig, src/PolyType.Roslyn/KnownSymbols.cs, src/PolyType.Roslyn/Model/DictionaryDataModel.cs, src/PolyType.Roslyn/Model/EnumerableDataModel.cs, src/PolyType.Roslyn/ModelGenerator/TypeDataModelGenerator.Dictionary.cs, src/PolyType.Roslyn/ModelGenerator/TypeDataModelGenerator.Enumerable.cs, src/PolyType.SourceGenerator/Model/DictionaryShapeModel.cs, src/PolyType.SourceGenerator/Model/EnumerableShapeModel.cs, src/PolyType.SourceGenerator/Parser/Parser.ModelMapper.cs, src/PolyType.SourceGenerator/SourceFormatter/SourceFormatter.Dictionary.cs, src/PolyType.SourceGenerator/SourceFormatter/SourceFormatter.Enumerable.cs, src/PolyType.TestCases/TestTypes.cs, src/PolyType/ReflectionProvider/ReflectionDictionaryTypeShape.cs, src/PolyType/ReflectionProvider/ReflectionEnumerableTypeShape.cs, tests/PolyType.SourceGenerator.UnitTests/CompilationHelpers.cs, tests/PolyType.SourceGenerator.UnitTests/CompilationTests.cs
The source generator compilation tests fail with `ExpandoObject`, but only in DEBUG builds where nullable annotations are checked. 
> 1>D:\source\PolyType\src\PolyType.TestCases\obj\Debug\net8.0\PolyType.SourceGenerator\PolyType.SourceGenerator.PolyTypeGenerator\PolyType.SourceGenerator.ShapeProvider.ExpandoObject.g.cs(21,51,21,175): error CS8631: The type 'System.Dynamic.ExpandoObject' cannot be used as type parameter 'TDictionary' in the generic type or method 'CollectionHelpers.AsReadOnlyDictionary<TDictionary, TKey, TValue>(TDictionary)'. Nullability of type argument 'System.Dynamic.ExpandoObject' doesn't match constraint type 'System.Collections.Generic.IDictionary<string, object>'.
Adding `ExpandoObject` to `TestTypes` revealed support limitations in your samples too, whose tests …
=> Add population support for collection types that explicitly implement collection interfaces.

src/PolyType.SourceGenerator/Analyzers/OnlySanctionedShapesAnalyzer.cs, src/PolyType.SourceGenerator/Parser/Parser.Diagnostics.cs, src/PolyType/Abstractions/IConstructorShape.cs, src/PolyType/Abstractions/IDictionaryTypeShape.cs, src/PolyType/Abstractions/IEnumTypeShape.cs, src/PolyType/Abstractions/IEnumerableTypeShape.cs, src/PolyType/Abstractions/IObjectTypeShape.cs, src/PolyType/Abstractions/IOptionalTypeShape.cs, src/PolyType/Abstractions/IParameterShape.cs, src/PolyType/Abstractions/IPropertyShape.cs, src/PolyType/Abstractions/ISurrogateTypeShape.cs, src/PolyType/Abstractions/ITypeShape.cs, src/PolyType/Abstractions/IUnionCaseShape.cs, src/PolyType/Abstractions/IUnionTypeShape.cs, src/PolyType/InternalImplementationsOnlyAttribute.cs, tests/PolyType.SourceGenerator.UnitTests/Analyzers/OnlySanctionedShapesAnalyzerTests.cs, tests/PolyType.Tests/Utilities/AggregatingTypeShapeProviderTests.cs
This ensures that we can add/remove members from it without fear of binary breaking changes.
Closes #171
Closes #176
=> Prevent external implementations of the shape interfaces

src/PolyType.Roslyn/Model/TypeDataModel.cs, src/PolyType.Roslyn/ModelGenerator/TypeDataModelGenerator.Dictionary.cs, src/PolyType.Roslyn/ModelGenerator/TypeDataModelGenerator.Enum.cs, src/PolyType.Roslyn/ModelGenerator/TypeDataModelGenerator.Enumerable.cs, src/PolyType.Roslyn/ModelGenerator/TypeDataModelGenerator.Object.cs, src/PolyType.Roslyn/ModelGenerator/TypeDataModelGenerator.Optional.cs, src/PolyType.Roslyn/ModelGenerator/TypeDataModelGenerator.Tuple.cs, src/PolyType.Roslyn/ModelGenerator/TypeDataModelGenerator.cs, src/PolyType.SourceGenerator/Parser/Parser.ModelMapper.cs, src/PolyType.SourceGenerator/Parser/Parser.cs, tests/PolyType.Tests/AssociatedTypesTests.cs
Previously, we supported 3rd party custom attributes that define associated types that appeared on types. With this change, we now recognize those attributes when they appear on properties and fields.
I had to rework the model for collecting associated types since we no longer know by the time we parse a type what the whole set of its associated types are.
Fixes #181
=> Discover associated types via attributes on members

src/PolyType/Abstractions/CollectionConstructionOptions.cs, tests/PolyType.Tests/CollectionConstructionOptionsTests.cs
Without this, deserializers have to manually copy properties from a 'template' options struct which may have comparers in it into a local variable for the struct in order to set `Capacity`. Since all these properties are declared as `init`, one cannot simply copy the struct into a local and then change Capacity -- it must be done all at construction time, which is tedious. And when we add properties to this struct, all those deserializers will drop that added property during their manual copy.
With the new copy constructor, the following syntax becomes an option:
```cs
CollectionConstructionOptions<TKey> options = new(this.optionsTemplate)
{
Capacity = count,
};
```
Alternative designs:
1. Use `record struct` so that C# users can say `this.optionsTemplate with { Capacity = count }`. This …
=> Add copy constructor to `CollectionConstructionOptions<TKey>`

src/PolyType.SourceGenerator/SourceFormatter/SourceFormatter.cs, tests/PolyType.SourceGenerator.UnitTests/CompilationTests.cs
When emitting shapes for types with obsolete properties, CS0612 may be emitted from generated code, with no way to suppress it from the user's project. We should suppress these within the source generator.
=> Suppress CS0612 obsolete warnings

src/PolyType/ReflectionProvider/CollectionConstructionInfo.cs, src/PolyType/ReflectionProvider/MemberAccessors/IReflectionMemberAccessor.cs, src/PolyType/ReflectionProvider/MemberAccessors/ReflectionEmitMemberAccessor.cs, src/PolyType/ReflectionProvider/MemberAccessors/ReflectionMemberAccessor.cs, src/PolyType/ReflectionProvider/ReflectionDictionaryTypeShape.cs, src/PolyType/ReflectionProvider/ReflectionEnumerableTypeShape.cs, src/PolyType/ReflectionProvider/ReflectionTypeShapeProvider.cs, tests/PolyType.Tests/ProviderUnderTest.cs, tests/PolyType.Tests/TypeShapeProviderTests.cs
When reflection with emit disabled encounters types with unsupported span-based constructors, it will silently fall back to using no constructor at all. This PR updates that behavior so that the same metadata is always reported, with an exception being thrown if the constructor is invoked.
=> Throw when attempting to call constructors accepting span in reflection without emit.

src/PolyType/SourceGenModel/SourceGenConstructorShape.cs, src/PolyType/SourceGenModel/SourceGenObjectTypeShape.cs
Fixes https://github.com/AArnott/Nerdbank.MessagePack/issues/485
Another concurrency bug in lazy initialization was causing unstable tests in Nerdbank.MessagePack where the deserializer would incorrectly report that required properties were missing from the deserialized stream when in fact they were present.
Before the fix in addition to tests failing randomly in my CI/PR, I was able to get it to fail using Run Until Failure in VS. The first time it failed on iteration 20. The second time it failed on the first iteration. With the fix, I got through 200 iterations without any failures.
I also improve the debugger display of the properties on these shapes.
=> Fix concurrency bug in lazy init of object constructor shapes

src/PolyType.Examples/CborSerializer/CborSerializer.Builder.cs, src/PolyType.Examples/Cloner/Cloner.Builder.cs, src/PolyType.Examples/ConfigurationBinder/ConfigurationBinder.Builder.cs, src/PolyType.Examples/DependencyInjection/ServiceProviderContext.Builder.cs, src/PolyType.Examples/JsonSerializer/JsonSerializer.Builder.cs, src/PolyType.Examples/ObjectMapper/Mapper.Builder.cs, src/PolyType.Examples/RandomGenerator/RandomGenerator.Builder.cs, src/PolyType.Examples/XmlSerializer/XmlSerializer.Builder.cs, src/PolyType.SourceGenerator/SourceFormatter/SourceFormatter.Dictionary.cs, src/PolyType.SourceGenerator/SourceFormatter/SourceFormatter.Enumerable.cs, src/PolyType/Abstractions/Delegates.cs, src/PolyType/Abstractions/IDictionaryTypeShape.cs, src/PolyType/Abstractions/IEnumerableTypeShape.cs, src/PolyType/Abstractions/IObjectTypeShape.cs, src/PolyType/ReflectionProvider/ReflectionDictionaryTypeShape.cs, src/PolyType/ReflectionProvider/ReflectionEnumerableTypeShape.cs, src/PolyType/SourceGenModel/SourceGenDictionaryTypeShape.cs, src/PolyType/SourceGenModel/SourceGenEnumerableTypeShape.cs, tests/PolyType.Tests/CollectionShapeTests.cs, tests/PolyType.Tests/CollectionsWithCapacityTests.cs, tests/PolyType.Tests/CollectionsWithComparersTests.cs, tests/PolyType.Tests/TypeShapeProviderTests.cs
Uses consistent terminology in default constructor delegates in both object and collection shapes. I've settled towards keeping `MutableCollectionConstructor` for the delegate type but `GetDefaultConstructor()` for the method that returns the mutable collection constructor. This keeps it consistent with `IConstructorShape` APIs and related helpers.
Contributes to #206.
=> Use consistent terminology for default constructor delegates.

src/PolyType.SourceGenerator/SourceFormatter/SourceFormatter.cs, tests/PolyType.SourceGenerator.UnitTests/CompilationTests.cs
In such an event, the user's project _already_ has to deal with such type name collisions and has likely suppressed the warning in their own usages of the types. But they can't do that within generated code, so PolyType should.
=> Suppress CS0436 warning in generated code

src/PolyType.Roslyn/ModelGenerator/TypeDataModelGenerator.Object.cs, src/PolyType.SourceGenerator/Parser/Parser.Diagnostics.cs, src/PolyType.SourceGenerator/Parser/Parser.ModelMapper.cs, src/PolyType.SourceGenerator/Parser/Parser.cs, src/PolyType.SourceGenerator/SourceFormatter/SourceFormatter.Enum.cs, src/PolyType.SourceGenerator/SourceFormatter/SourceFormatter.FSharpUnion.cs, src/PolyType.SourceGenerator/SourceFormatter/SourceFormatter.Function.cs, src/PolyType.SourceGenerator/SourceFormatter/SourceFormatter.Optional.cs, src/PolyType.SourceGenerator/SourceFormatter/SourceFormatter.Surrogate.cs, src/PolyType.SourceGenerator/SourceFormatter/SourceFormatter.Union.cs, tests/PolyType.Tests/AssociatedTypesTests.cs
* Extends associated type support to all type shape kinds, including surrogate types.
* Removes the restriction of associated types needing to be in the same assembly as the associating type.
Fix #239.
=> Extend associated type support to all type shape kinds.

src/PolyType.SourceGenerator/Parser/Parser.cs, src/PolyType/ReflectionProvider/ReflectionObjectTypeShape.cs, tests/PolyType.SourceGenerator.UnitTests/CompilationTests.DataContract.cs, tests/PolyType.Tests/DataContractShapeTests.cs
Fix https://github.com/eiriktsarpalis/PolyType/issues/286
=> Tolerate objects containing properties with duplicate property names in constructor resolution.

src/PolyType.Examples/JsonSerializer/JsonSerializer.cs, src/PolyType.Examples/ObjectMapper/Mapper.cs, src/PolyType/Utilities/Caching/MultiProviderTypeCache.cs, tests/PolyType.Tests/CacheTests.cs
Tweak the `MultiProviderTypeCache` APIs so that localized caches are resolved based on the `ITypeShape.Provider` property.
Fix #305.
FYI @AArnott
=> Tweak multi-provider cache APIs.
