eiriktsarpalis/PolyType

- src/TypeShape.Applications/CborSerializer/Converters/PrimitiveConverters.cs
- src/TypeShape.Applications/JsonSchema/JsonSchemaGenerator.cs
- src/TypeShape.Applications/RandomGenerator/RandomGenerator.Builder.cs
- src/TypeShape.Applications/XmlSerializer/Converters/PrimitiveConverters.cs
- tests/TypeShape.Tests/ClonerTests.cs
- tests/TypeShape.Tests/CounterTests.cs
- tests/TypeShape.Tests/JsonTests.cs
- tests/TypeShape.Tests/StructuralEqualityTests.cs
- tests/TypeShape.Tests/TestTypes.cs
- tests/TypeShape.Tests/TypeShapeProviderTests.cs
> Fix JsonSchema sample bug and add more null tests

- src/TypeShape.SourceGenerator/Helpers/RoslynHelpers.cs
- src/TypeShape.SourceGenerator/Model/ConstructorParameterShapeModel.cs
- src/TypeShape.SourceGenerator/Model/DictionaryShapeModel.cs
- src/TypeShape.SourceGenerator/Model/EnumerableShapeModel.cs
- src/TypeShape.SourceGenerator/Model/PropertyShapeModel.cs
- src/TypeShape.SourceGenerator/Parser/Parser.ModelMapper.cs
- src/TypeShape.SourceGenerator/SourceFormatter/SourceFormatter.Constructors.cs
- src/TypeShape.SourceGenerator/SourceFormatter/SourceFormatter.Dictionary.cs
- src/TypeShape.SourceGenerator/SourceFormatter/SourceFormatter.Enumerable.cs
- src/TypeShape.SourceGenerator/SourceFormatter/SourceFormatter.Properties.cs
- tests/TypeShape.Tests/JsonSchemaTests.cs
- tests/TypeShape.Tests/TestTypes.cs
> Fix suppressions for members containing nested nullability annotations

- src/TypeShape.Roslyn/ModelGenerator/TypeDataModelGenerator.Enum.cs
- src/TypeShape.Roslyn/ModelGenerator/TypeDataModelGenerator.cs
- tests/TypeShape.SourceGenerator.UnitTests/CompilationTests.cs
> Fix source generation for standalone enums

- src/TypeShape.SourceGenerator/Model/TypeDeclarationModel.cs
- src/TypeShape.SourceGenerator/Parser/Parser.cs
- src/TypeShape.SourceGenerator/SourceFormatter/SourceFormatter.cs
- tests/TypeShape.SourceGenerator.UnitTests/CompilationHelpers.cs
- tests/TypeShape.SourceGenerator.UnitTests/CompilationTests.cs
- tests/TypeShape.SourceGenerator.UnitTests/DiagnosticTests.cs
> Fix handling of non partial types and fix sourcegen unit tests.

- src/TypeShape.Roslyn/Model/PropertyDataModel.cs
- src/TypeShape.Roslyn/ModelGenerator/TypeDataModelGenerator.Object.cs
- src/TypeShape.Roslyn/ModelGenerator/TypeDataModelGenerator.Tuple.cs
- src/TypeShape.SourceGenerator/Helpers/RoslynHelpers.cs
- src/TypeShape.SourceGenerator/Model/ConstructorParameterShapeModel.cs
- src/TypeShape.SourceGenerator/Model/ConstructorShapeModel.cs
- src/TypeShape.SourceGenerator/Model/PropertyShapeModel.cs
- src/TypeShape.SourceGenerator/Parser/Parser.ModelMapper.cs
- src/TypeShape.SourceGenerator/Parser/Parser.cs
- src/TypeShape.SourceGenerator/SourceFormatter/SourceFormatter.Constructors.cs
- src/TypeShape.SourceGenerator/SourceFormatter/SourceFormatter.Object.cs
- src/TypeShape.SourceGenerator/SourceFormatter/SourceFormatter.Properties.cs
- src/TypeShape/ReflectionProvider/ReflectionObjectTypeShape.cs
- tests/TypeShape.Tests/TestTypes.cs
- version.json
> Add source gen support for explicitly opted in private members.

- .github/workflows/build.yml
- .github/workflows/update-docs.yml
- applications/ConfigurationBinder.AOT/ConfigurationBinder.AOT.csproj
- applications/ObjectMapper.AOT/ObjectMapper.AOT.csproj
- applications/RandomGeneratorApp.AOT/RandomGeneratorApp.AOT.csproj
- applications/SerializationApp.AOT/SerializationApp.AOT.csproj
- applications/SerializationApp.Reflection/SerializationApp.Reflection.csproj
- applications/ValidationApp.AOT/ValidationApp.AOT.csproj
- global.json
- src/PolyType.Roslyn/SourceWriter.cs
- src/PolyType.SourceGenerator/Parser/Parser.cs
- src/PolyType.TestCases/TestCase.cs
- src/PolyType.TestCases/TestTypes.cs
- tests/PolyType.Benchmarks/PolyType.Benchmarks.csproj
- tests/PolyType.SourceGenerator.UnitTests/PolyType.SourceGenerator.UnitTests.csproj
- tests/PolyType.Tests/PolyType.Tests.csproj
> Update to .NET 9 sdk

- src/PolyType.SourceGenerator/Helpers/RoslynHelpers.cs
- src/PolyType.SourceGenerator/Model/TypeId.cs
- src/PolyType.SourceGenerator/Model/TypeShapeModel.cs
- src/PolyType.SourceGenerator/Parser/Parser.ModelMapper.cs
- src/PolyType.SourceGenerator/Parser/Parser.cs
- src/PolyType.SourceGenerator/PolyTypeGenerator.cs
- src/PolyType.SourceGenerator/SourceFormatter/SourceFormatter.Constructors.cs
- src/PolyType.SourceGenerator/SourceFormatter/SourceFormatter.Dictionary.cs
- src/PolyType.SourceGenerator/SourceFormatter/SourceFormatter.Enum.cs
- src/PolyType.SourceGenerator/SourceFormatter/SourceFormatter.Enumerable.cs
- src/PolyType.SourceGenerator/SourceFormatter/SourceFormatter.ITypeShapeProvider.cs
- src/PolyType.SourceGenerator/SourceFormatter/SourceFormatter.Nullable.cs
- src/PolyType.SourceGenerator/SourceFormatter/SourceFormatter.Object.cs
- src/PolyType.SourceGenerator/SourceFormatter/SourceFormatter.Properties.cs
- src/PolyType.SourceGenerator/SourceFormatter/SourceFormatter.Type.cs
- src/PolyType.SourceGenerator/SourceFormatter/SourceFormatter.cs
- tests/PolyType.SourceGenerator.UnitTests/CompilationTests.cs
> Improve source generator resiliency when handling conflicting type names.

- src/PolyType.SourceGenerator/Parser/Parser.cs
- src/PolyType.SourceGenerator/SourceFormatter/SourceFormatter.Nullable.cs
- src/PolyType.SourceGenerator/SourceFormatter/SourceFormatter.Object.cs
> Add assembly name suffix to generated source provider.

- src/PolyType.SourceGenerator/SourceFormatter/SourceFormatter.Object.cs
> Fix source generator including unused unsafe accessors

- src/PolyType.Roslyn/Helpers/RoslynHelpers.cs
- src/PolyType.Roslyn/ModelGenerator/TypeDataModelGenerator.cs
- src/PolyType.SourceGenerator/Parser/Parser.Diagnostics.cs
- src/PolyType.SourceGenerator/Parser/Parser.ModelMapper.cs
- src/PolyType.SourceGenerator/Parser/Parser.cs
- src/PolyType.SourceGenerator/PolyType.SourceGenerator.csproj
- src/PolyType.SourceGenerator/PolyTypeKnownSymbols.cs
- src/PolyType.TestCases/ITestCase.cs
- src/PolyType.TestCases/TestCaseOfT.cs
- src/PolyType.TestCases/TestTypes.cs
- src/PolyType/Abstractions/TypeShapeKind.cs
- src/PolyType/PolyType.csproj
- src/PolyType/ReflectionProvider/ReflectionObjectTypeShape.cs
- src/PolyType/ReflectionProvider/ReflectionTypeShapeProvider.cs
- src/PolyType/TypeShapeAttribute.cs
- src/Shared/Helpers/ReflectionHelpers.cs
- tests/PolyType.SourceGenerator.UnitTests/CompilationTests.cs
- tests/PolyType.SourceGenerator.UnitTests/DiagnosticTests.cs
- tests/PolyType.Tests/ClonerTests.cs
- tests/PolyType.Tests/JsonTests.cs
- tests/PolyType.Tests/ProviderUnderTest.cs
- tests/PolyType.Tests/TypeShapeProviderTests.cs
> Add support for customizing TypeShape kinds via an attribute.

- .config/dotnet-tools.json
- Makefile
This supports the workflow I suggest in #82
> Add nbgv as a CLI tool

- docs/shape-providers.md
> Use a more canonical marshaller implementation in the docs

- docs/shape-providers.md
- src/PolyType.Roslyn/Helpers/RoslynHelpers.cs
- src/PolyType.SourceGenerator/Helpers/RoslynHelpers.cs
- src/PolyType.SourceGenerator/Parser/Parser.ModelMapper.cs
- src/PolyType.TestCases/TestTypes.cs
- src/PolyType/ReflectionProvider/ReflectionTypeShapeProvider.cs
- tests/PolyType.SourceGenerator.UnitTests/DiagnosticTests.cs
- tests/PolyType.Tests/TypeShapeProviderTests.cs
> Extend marshaller support to generic types

- Makefile
- src/Directory.Build.props
> Turn off warning-as-error in inner dev loop

- docs/core-abstractions.md
- docs/shape-providers.md
> Document derived type resolution

- src/PolyType.SourceGenerator/Parser/Parser.Diagnostics.cs
- tests/PolyType.SourceGenerator.UnitTests/DiagnosticTests.cs
> Rename diagnostic code prefix from TS to PT

- src/PolyType.TestCases/TestTypes.cs
> Add `SortedList<K, V>` as a test type

- .github/workflows/build.yml
- exclusion.dic
- src/PolyType.SourceGenerator/Model/TypeExtensionModel.cs
- src/PolyType.SourceGenerator/Parser/Parser.ModelMapper.cs
- src/PolyType.SourceGenerator/Parser/Parser.cs
- src/PolyType/GenerateShapeAttribute.cs
- src/PolyType/GenerateShapeForAttribute.cs
- src/PolyType/ReflectionProvider/ReflectionTypeShapeProvider.cs
- tests/PolyType.Tests/TypeShapeProviderTests.cs
> Add support for shape extensibility via GenerateShape* attributes.

- src/PolyType.SourceGenerator/Parser/Parser.ModelMapper.cs
- tests/PolyType.SourceGenerator.UnitTests/CompilationTests.cs
> Fix handling of labeled tuples in properties.

- src/PolyType.SourceGenerator/Helpers/RoslynHelpers.cs
- src/PolyType.SourceGenerator/Parser/Parser.ModelMapper.cs
- src/PolyType.SourceGenerator/Parser/Parser.cs
- tests/PolyType.SourceGenerator.UnitTests/CompilationTests.cs
> Fix tuple name normalization in all locations.

- src/PolyType.SourceGenerator/Helpers/RoslynHelpers.cs
- src/PolyType.SourceGenerator/Model/AssociatedTypeId.cs
- src/PolyType.SourceGenerator/Model/TypeShapeModel.cs
- src/PolyType.SourceGenerator/Parser/Parser.ModelMapper.cs
- src/PolyType.SourceGenerator/Parser/Parser.cs
- src/PolyType.SourceGenerator/SourceFormatter/SourceFormatter.Dictionary.cs
- src/PolyType.SourceGenerator/SourceFormatter/SourceFormatter.Enum.cs
- src/PolyType.SourceGenerator/SourceFormatter/SourceFormatter.Enumerable.cs
- src/PolyType.SourceGenerator/SourceFormatter/SourceFormatter.FSharpUnion.cs
- src/PolyType.SourceGenerator/SourceFormatter/SourceFormatter.Function.cs
- src/PolyType.SourceGenerator/SourceFormatter/SourceFormatter.Object.cs
- src/PolyType.SourceGenerator/SourceFormatter/SourceFormatter.Optional.cs
- src/PolyType.SourceGenerator/SourceFormatter/SourceFormatter.Surrogate.cs
- src/PolyType.SourceGenerator/SourceFormatter/SourceFormatter.TypeShapeProvider.cs
- src/PolyType.SourceGenerator/SourceFormatter/SourceFormatter.Union.cs
- src/PolyType.SourceGenerator/SourceFormatter/SourceFormatter.cs
- src/PolyType/SourceGenModel/SourceGenTypeShape.cs
> Optimize the SourceGenTypeShapeProvider.GetTypeShape method.

- src/PolyType.SourceGenerator/Helpers/RoslynHelpers.cs
- src/PolyType.TestCases/TestTypes.GlobalNamespace.cs
- src/PolyType.TestCases/TestTypes.cs
> Fix global namespace handling in the source generator.

- src/PolyType.Examples/DependencyInjection/ServiceProviderContext.Builder.cs
- src/PolyType.Examples/JsonSchema/JsonSchemaGenerator.cs
- src/PolyType.Examples/ObjectMapper/Mapper.cs
- src/PolyType.TestCases/TestCaseOfT.cs
- src/PolyType/ITypeShapeProvider.cs
- src/PolyType/TypeShapeProviderExtensions.cs
- src/PolyType/Utilities/Caching/TypeCache.cs
- tests/PolyType.SourceGenerator.UnitTests/CompilationTests.cs
- tests/PolyType.Tests/CacheTests.cs
- tests/PolyType.Tests/CborTests.cs
- tests/PolyType.Tests/CollectionsWithCapacityTests.cs
- tests/PolyType.Tests/EnumMemberShapeTests.cs
- tests/PolyType.Tests/JsonSchemaTests.cs
- tests/PolyType.Tests/JsonTests.cs
- tests/PolyType.Tests/ProviderUnderTest.cs
- tests/PolyType.Tests/TypeShapeProviderExtensionsTests.cs
- tests/PolyType.Tests/TypeShapeProviderTests.cs
> Revise ITypeShapeResolver.GetTypeShape extensions.

- src/PolyType/Debugging/DebuggerProxies.cs
- tests/PolyType.Tests/TypeShapeProviderTests.cs
> Ensure debug proxies expose all shape properties.

- .github/workflows/markdown-link-check.yml
Likely cause of failing CI
Reverts eiriktsarpalis/PolyType#281
> Revert "ci(deps): bump becheran/mlc from 0.15.4 to 1.0.0"

- src/PolyType.SourceGenerator/Parser/Parser.cs
- src/PolyType/ReflectionProvider/ReflectionTypeShape.cs
- tests/PolyType.SourceGenerator.UnitTests/CompilationTests.FunctionShapes.cs
> Filter explicitly implemented events.
